# Generated by Django 5.1.7 on 2025-04-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('text', models.TextField()),
                ('generated_video', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
        ),
    ]
